#!/bin/bash -e

echo "Launching conjur container..."
docker-compose up -d conjur

echo "Waiting for Conjur to be ready"
docker-compose exec conjur conjurctl wait

echo "Adding database credentials to Conjur..."
source ./_conjur.sh

admin_api_key=$(docker-compose exec conjur conjurctl role retrieve-key dev:user:admin | tr -d '\r')

conjur_cli "$admin_api_key" variable values add db/password "$(< ../secrets/db.password)"
conjur_cli "$admin_api_key" variable values add db/ssh_key "$(< ../secrets/id_insecure)"
conjur_cli "$admin_api_key" variable values add myapp_tls/ssl_key "$(< ../secrets/proxy_tls.key)"

echo "Done"
