#!/bin/bash -e

source ./_conjur.sh

admin_api_key=$(docker-compose exec conjur conjurctl role retrieve-key dev:user:admin | tr -d '\r')
ansible_api_key=$(conjur_cli "$admin_api_key" host rotate_api_key -h ansible | tr -d '\r')

export CONJUR_AUTHN_API_KEY="$ansible_api_key"

echo "Launching Ansible runner and PostgreSQL..."
docker-compose up -d pg ansible_secretless

echo "Running Anisible playbook..."
docker-compose run --rm \
                   --no-deps \
                   -e ANSIBLE_HOST_KEY_CHECKING=False \
                   -e CONJUR_AUTHN_API_KEY="$ansible_api_key" \
                   ansible ansible-playbook postgresql.yml

echo "Done"
