#!/bin/bash -e

help_and_exit() {
  local retval=${1:-1}
  cat <<EOF
This script detects if you're in "dev" mode by the existence of
the secretless-dev container.  That container will exist only if
the development process was started using the "./dev" command.

If in dev mode, this script will exit with an error, and notify
you that you should use the "./start" command before running tests.
The "./dev" command cannot be used for tests since it uses static
fixtures instead of the dynamically generated ones needed for the
tests. See the README.md in this directory for more information.

Options:
  -v verbose mode; provides more verbose output for test cases
EOF
  exit "$retval"
}

export VERBOSE=false

while getopts :v opt; do
    case $opt in
        v) VERBOSE=true;;
       \?) echo "Unknown option -$OPTARG"; help_and_exit 1;;
    esac
done

# Automatically detect if we're devmode based on the existence
# of the secretless-dev container.  We assume that you started
# your workflow using `./dev` if you are developing, and this
# command will use the secretless-dev container.


if [[ ! -z $(docker compose ps -q secretless-dev) ]]; then
  echo "Please run the ./start script before running this script"
  exit 1
fi

docker compose run --rm --no-deps \
  -e SECRETLESS_HOST="secretless" \
  test bash -c "go test -v ./test/connector/tcp/mysql/tests"
