#!/bin/bash

set -euo pipefail

# load the environment with the test config
source load_test_env_vars

# delete the password if it exists, and swallow errors if not
security delete-generic-password \
  -a $ACCOUNT \
  -s $SERVICE \
  &>/dev/null \
  || true
