#!/bin/bash -ex

mssql_host=mssql
while getopts :dm:s: opt; do
    case $opt in
        d) dev_mode=true;;
        m) mssql_host=${OPTARG};;
        s) secretless_host=${OPTARG};;
       \?) echo "Unknown option -$OPTARG"; exit 1;;
    esac
done
# If the secretless host is not explicitly set on the command line,
# then use one of the default names (either secretless or
# secretless-dev, depending on whether testing is being done in
# development mode) for the secretless host.
if [[ -z $secretless_host ]]; then
    secretless_host=secretless
    if [[ "$dev_mode" = true ]]; then
        secretless_host=secretless-dev
    fi
fi

./stop

docker-compose build

# the order of the services is important. mssql must be up before we start secretless
docker-compose up -d $mssql_host

time ./wait_for_mssql -m $mssql_host
docker-compose logs $mssql_host

docker-compose up -d $secretless_host
