#!/bin/bash

export SECRETLESS_HOST=secretless
if [[ ! -z $(docker-compose ps -q secretless-dev) ]]; then
  export SECRETLESS_HOST=secretless-dev
fi

docker-compose run \
  -e SECRETLESS_HOST="$SECRETLESS_HOST" \
  --rm \
  --no-deps \
  test bash -c "go test -v ./test/connector_tests/tcp_connectors/mssql_connector"

# print secretless logs after tests run
ret=$?
docker-compose logs $SECRETLESS_HOST
exit $ret
