#!/bin/bash

mssql_is_up() {
    docker-compose logs mssql | grep "SQL Server is now ready for client connections"
}

# TODO: Use bash-lib for this function once it is implemented there
max_tries=300
cnt=0
until mssql_is_up || (( cnt == max_tries )); do
  (( cnt++ ))
  sleep 1
done

timed_out=$(( cnt == max_tries ))
if [[ $timed_out -eq 1 ]]; then
  echo "MSSQL Server failed to start"
  exit 1
fi
