#!/bin/bash -e

# Automatically detect if we're devmode based on the existence
# of the secretless-dev container.  We assume that you started
# your workflow using `./dev` if you are developing, and this
# command will use the secretless-dev container.
secretless_host="secretless-2019"
if [[ ! -z $(docker-compose ps -q secretless-2019-dev) ]]; then
  secretless_host=secretless-2019-dev
fi

../test -s $secretless_host
