#!/bin/bash -e

help_and_exit() {
  local retval=${1:-1}
  cat <<EOF
Options:
  -d runs tests against secretless-dev container
  -b runs benchmarks
  -v verbose mode; provides more verbose output for test cases
EOF
  exit "$retval"
}

export SECRETLESS_HOST=secretless
export VERBOSE=false
benchmark=false
while getopts :bdv opt; do
    case $opt in
        b) benchmark=true;;
        d) SECRETLESS_HOST=secretless-dev;;
        v) VERBOSE=true;;
       \?) echo "Unknown option -$OPTARG"; help_and_exit 1;;
    esac
done

if $benchmark; then
  # first set PG_ADDRESS and SECRETLESS_ADDRESS
  pg_cid=$(docker-compose ps -q pg)
  secretless_cid=$(docker-compose ps -q $SECRETLESS_HOST)
  pg_ip=$(docker inspect \
    -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $pg_cid)
  secretless_ip=$(docker inspect \
    -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $secretless_cid)

  export PG_ADDRESS=$pg_ip:5432
  export SECRETLESS_ADDRESS=$secretless_ip:5432

  echo "++++++++++++++++++++++++++++++++++++++"
  echo ""
  echo "Running PostgreSQL benchmarks ..."
  echo ""
  echo "++++++++++++++++++++++++++++++++++++++"
  echo "working with $SECRETLESS_HOST"
  docker-compose run \
    --rm \
    --no-deps \
    test \
    bash -c '
      echo "--- QUERYING POSTGRES DIRECTLY ---" && \
      BENCH_ADDRESS=$PG_ADDRESS go test -v -bench=. -test.benchtime=10s ./test/pg_handler/bench_test.go | tee bench.old && \

      echo "--- QUERYING VIA SECRETLESS ---" && \
      BENCH_ADDRESS=$SECRETLESS_ADDRESS go test -v -bench=. -test.benchtime=10s ./test/pg_handler/bench_test.go | tee bench.new && \

      echo "--- COMPARING BENCHMARKS ---" && \
      benchcmp bench.old bench.new
    '
else
  docker-compose run \
  --rm \
  --no-deps \
  test
fi

