#!/bin/bash -e

help_and_exit() {
  local retval=${1:-1}
  cat <<EOF
Options:
  -d runs tests against secretless-dev container
  -v verbose mode; provides more verbose output for test cases
EOF
  exit "$retval"
}

export SECRETLESS_HOST=secretless
export VERBOSE=false
while getopts :dv opt; do
    case $opt in
        d) SECRETLESS_HOST=secretless-dev;;
        v) VERBOSE=true;;
       \?) echo "Unknown option -$OPTARG"; help_and_exit 1;;
    esac
done

docker-compose run \
  --rm \
  --no-deps \
  test
