#!/bin/bash
set -e

echo "Waiting for Secretless to start"
docker-compose exec -T $1 sh -c "
  while ! ls /sock/mysql.sock > /dev/null 2>&1;
    do
      >&2 printf '. '
      sleep 1
  done
  "

echo ""
>&2 echo "Secretless is up - continuing "
