---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "secretless-config"
data:
  secretless.yml: |
    listeners:
      - name: http_good_basic_auth
        debug: true
        protocol: http
        address: 0.0.0.0:3000

    handlers:
      - name: http_good_basic_auth_handler
        type: basic_auth
        listener: http_good_basic_auth
        debug: true
        match:
          - ^http.*
        credentials:
          - name: username
            provider: literal
            id: test-secret#username
          - name: password
            provider: literal
            id: test-secret#password

---
apiVersion: v1
kind: Pod
metadata:
  name: "example-usage"
  annotations:
    sidecar-injector.cyberark.com/inject: "yes"
    sidecar-injector.cyberark.com/config: "secretless-config"
    sidecar-injector.cyberark.com/injectType: "secretless"
    sidecar-injector.cyberark.com/containerName: "yes-container"
  labels:
    app: example-usage
spec:
  containers:
  - name: app
    env:
      - name: http_proxy
        value: "http://0.0.0.0:3000"
    image: googlecontainer/echoserver:1.1
#    run "curl localhost:8080" and observe the authorization header
