---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "secretless-config"
data:
  secretless.yml: ""

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "authenticator-config"
data:
  CONJUR_VERSION: "4"
  CONJUR_APPLIANCE_URL: "path/to/conjur"
  CONJUR_AUTHN_URL: "path/to/conjur/auth"
  CONJUR_ACCOUNT: "some account"
  CONJUR_SSL_CERTIFICATE: "x"
  CONJUR_AUTHN_LOGIN: "some login"

---
apiVersion: v1
kind: Pod
metadata:
  name: "beep"
  annotations:
    sidecar-injector.cyberark.com/inject: "yes"
    sidecar-injector.cyberark.com/config: "secretless-config"
    sidecar-injector.cyberark.com/injectType: "secretless"
    sidecar-injector.cyberark.com/containerMode: "yes-mode"
    sidecar-injector.cyberark.com/containerName: "yes-container"
  labels:
    app: sleep
spec:
  containers:
  - name: sleep
    image: everpeace/curl-jq
    command: ["/bin/sleep","infinity"]
