engines:
  golint:
    enabled: true
    exclude_patterns:
    - "**/"                # exclude all
    - "!./cmd/"            # unexclude just the ones we want to lint
    - "!./internal/"
    - "!./pkg/"
    - "!./test/"
  shellcheck:
    enabled: true
    checks:
      # Disable 'Not following' check - it doesn't handle ". ./script.sh" properly
      SC1091:
        enabled: false
      SC2148:
        enabled: false
