project_name: secretless-broker

builds:
- binary: summon2
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  goarch:
  - amd64
  main: ./cmd/summon2/main.go

- binary: secretless-broker
  env:
  - CGO_ENABLED=1
  flags: --tags netgo
  goos:
  - linux
  goarch:
  - amd64
  ldflags: -s -w -linkmode external -extldflags "-static"
  main: ./cmd/secretless-broker/main.go

archive:
  files:
    - CHANGELOG.md
    - LICENSE.md
    - README.md
  format_overrides:
    - goos: windows
      format: zip
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
  wrap_in_directory: true

checksum:
  name_template: 'SHA256SUMS.txt'

dist: ./dist/goreleaser

nfpm:
  bindir: /usr/bin
  description: Secures your apps by making them Secretless
  empty_folders:
  - /usr/local/lib/secretless
  formats:
  - deb
  - rpm
  homepage: https://secretless.io
  license: "Apache 2.0"
  maintainer: CyberArk Maintainers <conj_maintainers@cyberark.com>
  name_template: "{{.ProjectName}}_{{.Version}}_{{.Arch}}"
  vendor: CyberArk

snapshot:
  name_template: "{{ .Tag }}-next"

release:
  disable: true
  prerelease: auto
