FROM golang:1.11beta2-stretch
MAINTAINER Conjur Inc.

RUN apt-get update && \
    apt-get install -y curl \
                       jq \
                       less \
                       vim

ENV ROOT_DIR=/secretless

WORKDIR $ROOT_DIR

RUN groupadd -r secretless \
             -g 777 && \
    useradd -c "secretless runner account" \
            -g secretless \
            -u 777 \
            -m \
            -r \
            secretless && \
    mkdir -p /usr/local/lib/secretless \
             /sock && \
    chown secretless:secretless /usr/local/lib/secretless \
                                /sock

RUN go get -u github.com/jstemmer/go-junit-report && \
    go get github.com/smartystreets/goconvey && \
    go get golang.org/x/tools/cmd/goimports

COPY go.mod go.sum /secretless/

# https://github.com/golang/go/issues/26610
RUN go list -e $(go list -f '{{.Path}}' -m all 2>/dev/null)

# TODO: Expand this with build args when we support other arches
ENV GOOS=linux \
    GOARCH=amd64 \
    CGO_ENABLED=1

COPY . .

# Not strictly needed but we might as well do this step too since
# the dev may want to run the binary
RUN go build -o dist/$GOOS/$GOARCH/secretless ./cmd/secretless && \
    go build -o dist/$GOOS/$GOARCH/summon2 ./cmd/summon2 && \
    ln -s $ROOT_DIR/dist/$GOOS/$GOARCH/secretless /usr/local/bin/ && \
    ln -s $ROOT_DIR/dist/$GOOS/$GOARCH/summon2 /usr/local/bin/
