FROM golang:1.13-alpine
MAINTAINER Conjur Inc.
LABEL id="secretless-test-runner"

ENTRYPOINT [ "go", "test", "-v", "-timeout", "3m" ]
WORKDIR /secretless

RUN apk add -u curl \
               gcc \
               git \
               mercurial \
               musl-dev

COPY go.mod go.sum /secretless/
COPY third_party/ /secretless/third_party

RUN go mod download

COPY . .

# Adding a comment to the end to trigger a change.
