FROM golang:1.11beta2-alpine
MAINTAINER Conjur Inc.
LABEL id="secretless-test-runner"

ENTRYPOINT [ "go", "test", "-v", "-timeout", "3m" ]
WORKDIR /secretless

RUN apk add -u curl gcc git musl-dev

COPY go.mod go.sum /secretless/

# https://github.com/golang/go/issues/26610
RUN go list -e $(go list -f '{{.Path}}' -m all 2>/dev/null)

COPY . .
