FROM golang:1.8
MAINTAINER Conjur Inc.

RUN go get -u github.com/jstemmer/go-junit-report
RUN go get github.com/tools/godep
RUN go get github.com/smartystreets/goconvey
RUN apt-get update && apt-get install -y vim jq curl

COPY . .

WORKDIR /go/src/github.com/kgilpin/secretless-pg

EXPOSE 5432

ENTRYPOINT [ "./bin/linux/amd64/secretless-pg", "-config", "config.docker.yaml" ]
