FROM golang:1.10-stretch
MAINTAINER Conjur Inc.

RUN apt-get update && \
    apt-get install -y curl \
                       jq \
                       less \
                       vim

WORKDIR /go/src/github.com/conjurinc/secretless

RUN go get -u github.com/golang/dep/cmd/dep && \
    go get -u github.com/jstemmer/go-junit-report && \
    go get github.com/smartystreets/goconvey && \
    go get golang.org/x/tools/cmd/goimports

COPY Gopkg.toml Gopkg.lock /go/src/github.com/conjurinc/secretless/

RUN dep ensure --vendor-only

COPY . .

# Not strictly needed but we might as well do this step too since
# the dev may want to run the binary
RUN go build -o bin/$GOOS/$GOARCH/secretless ./cmd/secretless && \
    go build -o bin/$GOOS/$GOARCH/summon2 ./cmd/summon2
