#!/bin/bash -e

local_test=false
while getopts :l opt; do
    case $opt in
        l) local_test=true ;;
       \?) echo "Unknown option -$OPTARG"; exit 1;;
    esac
done

docker_args=""
if $local_test; then
  docker_args="-v $(cd ../..; pwd):/secretless"
fi

docker run \
  --rm \
  -w /secretless/test/summon2/ \
  $docker_args \
  secretless-dev \
  bash -ecx "
    go test -v .
  "
