#!/usr/bin/env bash

# this is for local testing

export TEST_ROOT="/secretless/test/connector/tcp/mssql"
export DB_PROTOCOL="mssql"
export DB_HOST_TLS="mssql-2017-cu1"
export DB_HOST_NO_TLS="mssql-2017-cu1"
export DB_PORT="1434"
export DB_USER="sa"
export DB_PASSWORD="yourStrong()Password"
export SECRETLESS_HOST="127.0.0.1"
export SECRETLESS_PORT="2224"

cd ..
go test -v
