#!/bin/bash -e

CURRENT_DIR=$(dirname $0)

echo "Deploying..."
kubectl delete crd configurations.secretless.io || true

kubectl delete service secretless-broker || true
kubectl delete service secretless-broker-external || true

kubectl delete clusterrole secretless-crd || true
kubectl delete rolebinding secretless-crd || true
kubectl delete clusterrolebinding secretless-crd || true
kubectl delete serviceaccount secretless-crd || true

kubectl delete deployment secretless-k8s-test
