apiVersion: v1
kind: Service
metadata:
  name: {{ include "cyberark-sidecar-injector.fullname" . }}
  labels:
    app: {{ include "cyberark-sidecar-injector.name" . }}
    chart: {{ include "cyberark-sidecar-injector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: {{ include "cyberark-sidecar-injector.name" . }}
    release: {{ .Release.Name }}
