---
# This role is allow to [get] the credentials secret
# in the namespace where this manifest is applied
kind: ServiceAccount
apiVersion: v1
metadata:
  name: "{{ include "cyberark-sidecar-injector.fullname" . }}"
