#!/bin/bash -e

# Env vars
. ./app_constants.sh

# Note: In future versions of k8s we'll be able to replace this code
# with the k8s "wait" command:
# https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#wait
delete_ns() {
  echo "Deleting namespace '$1'..."
  # We don't care about the output of this command, only its return return code:
  # success means there was something to delete, and that we must wait for
  # deletion to fully process.  Failure means there was nothing to delete and
  # we can return early.
  if ! kubectl delete namespace "$1" > /dev/null 2>&1; then
    return 0
  fi

  # As long as we can still "get" the namespace, the deletion isn't done.
  while kubectl get namespace "$1" > /dev/null 2>&1; do 
    printf "."
    sleep 2
  done
}

delete_ns "$BACKEND_NAMESPACE"
delete_ns "$APP_NAMESPACE"

echo "Namespaces cleared"
