#!/bin/bash -e

new_password="$1"
if [[ -z $new_password ]]; then
  echo "usage: $0 <new-password>"
  exit 1
fi

db_username=quick_start

# Set the new password.
echo "ALTER ROLE $db_username WITH PASSWORD '$new_password'" | psql -U postgres

# Close all the connections, forcing them to reconnect.
cat <<KILL_CONNECTIONS | psql -U postgres
SELECT
    pg_terminate_backend(pid)
FROM
    pg_stat_activity
WHERE
    pid <> pg_backend_pid()
;
KILL_CONNECTIONS
