FROM postgres:9.3

COPY pg_hba.conf /etc/
COPY pg_hba test.sql /docker-entrypoint-initdb.d/
COPY ./etc/server.crt /var/lib/postgresql/
COPY ./etc/server.key /var/lib/postgresql/

RUN chown postgres:postgres /var/lib/postgresql/server.key
RUN chown postgres:postgres /var/lib/postgresql/server.crt
RUN chmod 0600 /var/lib/postgresql/server.key
