#!/bin/bash -ex

platform=$(go run ../print_platform.go)

pg_host_port=$(docker-compose port pg 5432)
pg_port="${pg_host_port##*:}"

exec env PG_ADDRESS="localhost:$pg_port" \
  PG_PASSWORD=test \
  "../../dist/$platform/amd64/secretless-broker" \
  -config secretless.dev.yml
