#!/bin/bash -ex

platform=$(go run ../print_platform.go)

pushd ../.. &>/dev/null
  go build -o "dist/$platform/amd64/secretless" ./cmd/secretless
popd &>/dev/null

./run_dev &

sleep 2

go test -v .

kill "$!"
