#!/bin/bash -ex

./stop

cd ./etc
  ./cert.sh
cd ..

docker-compose build

docker-compose up \
  -d \
  pg

./wait-for-pg

# start secretless once pg is running
pg_cid=$(docker-compose ps -q pg)
pg_ip=$(docker inspect \
  -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $pg_cid)
export PG_ADDRESS=$pg_ip:5432
export PG_ADDRESS_TLS=$pg_ip:5432?sslmode=require
docker-compose up \
  -d \
  secretless

sleep 2
