#!/bin/bash -e

echo "Waiting for Secretless to start"

# single quotes are intentional:
# shellcheck disable=SC2016
docker-compose exec -T test bash -ec '
counter=0
while ! wget --quiet --output-document - http://secretless:5335/ready > /dev/null 2>&1; do
    if expr $counter = 5 > /dev/null; then
      echo ""
      echo "Timed out waiting for Secretless"
      exit 1
    fi
    let "counter = $counter + 1"
    >&2 printf ". "
    sleep 1
done
'

echo "Secretless is up - continuing "
echo ""
echo "Running tests"
echo ""

docker-compose exec -T test go test -v -count=1 ./test/connector/http/generic/...
