FROM phusion/baseimage

COPY ./id_insecure.pub /tmp/id_insecure.pub
RUN cat /tmp/id_insecure.pub >> /root/.ssh/authorized_keys

RUN rm -f /etc/service/sshd/down

# Regenerate SSH host keys. baseimage-docker does not contain any, so you
# have to do that yourself. You may also comment out this instruction; the
# init system will auto-generate one during boot.
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh
