FROM secretless-dev

RUN apt-get update && apt-get install -y autoconf bison build-essential \
  libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev \
  libgdbm3 libgdbm-dev git-core

RUN git clone https://github.com/rbenv/rbenv.git ~/.rbenv
RUN git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build

RUN ~/.rbenv/bin/rbenv install 2.3.3 && ~/.rbenv/bin/rbenv global 2.3.3
RUN ~/.rbenv/shims/gem install -N conjur-cli -v 6
RUN ln -sf ~/.rbenv/shims/conjur /usr/local/bin/
