---
kind: Secret
apiVersion: v1
metadata:
  name: "{{ include "cyberark-sidecar-injector.fullname" . }}-certs"
type: Opaque
data:
  cert.pem:  {{ (required "A valid .Values.cert entry required!" .Values.cert) | b64enc | quote }}
  key.pem: {{ (required "A valid .Values.key entry required!" .Values.key) | b64enc | quote }}
