# kics-scan disable=611ab018-c4aa-4ba2-b0f6-a448337509a6
# NOTE: Example for illustrative purposes only. For production use, consider using
# a non-default namespace.
apiVersion: "secretless.io/v1"
kind: Configuration
metadata:
  name: secretless-example-config
spec:
  listeners:
    - name: http_good_basic_auth
      protocol: http
      socket: /sock/.s.proxy.8080

  handlers:
    - name: http_good_basic_auth_handler
      type: basic_auth
      listener: http_good_basic_auth
      match:
        - ^http.*
      credentials:
        - name: username
          provider: literal
          id: someusername
        - name: password
          provider: literal
          id: somepassword
