#!/bin/bash -ex

platform=$(go run ../print_platform.go)

pushd ../..
  go build -o "dist/$platform/amd64/secretless" ./cmd/secretless
popd

mysql_host_port=$(docker-compose port mysql 3306)
mysql_port="${mysql_host_port##*:}"

exec env MYSQL_HOST="localhost" \
  MYSQL_PORT="$mysql_port" \
  MYSQL_PASSWORD=testpass \
  "../../dist/$platform/amd64/secretless" \
  -f secretless.dev.yml
