#!/bin/bash -ex

SECRETLESS_HOST=secretless
while getopts :d opt; do
    case $opt in
        d) SECRETLESS_HOST=secretless-dev;;
       \?) echo "Unknown option -$OPTARG"; exit 1;;
    esac
done

./stop

docker-compose build

docker-compose up \
  -d \
  mysql mysql_no_tls

./wait-for-mysql mysql_no_tls
./wait-for-mysql mysql

# generate fixtures
## valid-ca.pem
## NOTE this should come before secretless.yml because it is required by the autogen
docker-compose exec -T mysql cat /var/lib/mysql/ca.pem > fixtures/valid-ca.pem
## secretless.yml
touch fixtures/secretless.yml
docker-compose run --rm test \
  bash -c "
  cd test/mysql_handler && \
  go run cmd/generate_secretless_config.go
"

# start secretless once mysql is running
docker-compose up \
  -d \
  ${SECRETLESS_HOST}

./wait-for-secretless ${SECRETLESS_HOST}
