#!/bin/bash -ex

./stop

docker-compose build

docker-compose up \
  -d \
  mysql mysql_no_tls

./wait-for-mysql mysql_no_tls
./wait-for-mysql mysql

# start secretless once mysql is running
docker-compose up \
  -d \
  secretless

./wait-for-secretless secretless

