#!/bin/bash -ex

./stop

docker-compose build

docker-compose up \
  -d \
  mysql

./wait-for-mysql

# start secretless once mysql is running
mysql_cid=$(docker-compose ps -q mysql)
mysql_ip=$(docker inspect \
  -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $mysql_cid)
export MYSQL_HOST=$mysql_ip
docker-compose up \
  -d \
  secretless

sleep 2
