#!/bin/bash
set -e

echo "Waiting for MySQL to start"
docker-compose exec -T $1 bash -c "
  while ! mysqladmin -psecurerootpass status > /dev/null 2>&1;
    do
      >&2 printf '. '
      sleep 1
  done
  "

echo ""
>&2 echo "MySQL is up - continuing "
