apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: secretless-sidecar-injector-webhook-cfg
  labels:
    app: secretless-sidecar-injector
webhooks:
  - name: sidecar-injector.cyberark.com
    clientConfig:
      service:
        name: ${service}
        namespace: ${namespace}
        path: "/mutate"
      caBundle: ${CA_BUNDLE}
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        secretless-sidecar-injector: enabled
