apiVersion: v1
kind: Service
metadata:
  name: cyberark-sidecar-injector-webhook-svc
  labels:
    app: cyberark-sidecar-injector
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: cyberark-sidecar-injector
