apiVersion: v1
kind: Service
metadata:
  name: cyberark-sidecar-injector
  labels:
    app: cyberark-sidecar-injector
spec:
  ports:
  - port: 443
    targetPort: https
  selector:
    app: cyberark-sidecar-injector
