#!/bin/bash -e

echo "Creating users 'alice' and 'bob' using a 'curl' request to 'http://myapp'"

docker-compose run --rm client curl -X POST myapp --data @alice.json
echo

docker-compose run --rm client curl -X POST myapp --data @bob.json
echo

echo "Listing all users using a 'curl' request to 'http://myapp'"

docker-compose run --rm client /bin/sh -c 'curl myapp | jq'
echo
