#!/bin/bash -ex

local_test=false
while getopts :l opt; do
    case $opt in
        l) local_test=true ;;
       \?) echo "Unknown option -$OPTARG"; exit 1;;
    esac
done

report_dir="./test-coverage"
mkdir -p "$report_dir"
chmod 777 "$report_dir"

if $local_test; then
  docker_args="-v $(cd ../..; pwd):/secretless"
fi

docker compose run \
  --rm \
  --no-deps \
  $docker_args \
  test
