name: CI

on:
  # Run once daily at 12 AM UTC, 8 PM EST
  schedule:
    - cron: '0 0 * * *'

  # Run this on pushes to any branch
  push:

jobs:
  unit_test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Unit tests
        run: ./bin/test_unit

  build_and_test:
    name: Build and Functional Tests on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: ./bin/build
      - name: Integration tests
        run: ./bin/test

  osx_test:
    name: Functional Tests on macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      # Cache go module dependencies based on go.sum to improve workflow execution time.
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # Install go1.17
      - uses: actions/setup-go@v3
        with:
          go-version: '~1.17.0'
      # Get go version
      - run: go version
      # Download go modules
      - run: go mod download
      # Run keychain tests
      - run: cd test/providers/keychain && ./start && ./test && ./stop
